### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by adl1995** [manosim/gitify#283]
I just cloned the repository and ran `npm install`, however, when I run `npm start`, I get the following error:

```
TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/home/gitify-electron-react-app/main.js:26:43)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at loadApplicationPackage (/home/gitify-electron-react-app/node_modules/electron/dist/resources/default_app.asar/main.js:288:12)
    at Object.<anonymous> (/home/gitify-electron-react-app/node_modules/electron/dist/resources/default_app.asar/main.js:330:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

It fails at this line of code:

`path: process.execPath.match(/.*?\.app/)[0]`

**Comment by manosim** [comment]
Hello @adl1995! Version 2 is now out and is a complete rewrite - can you try with v2? Let me know if the issue still exists!

**Comment by adl1995** [comment]
@manosim - I just realized this is only available for OS X. So, I'll close this issue as I'm on Linux. But, do let me know if you have any future plans to release your application for Linux.

Thanks!
