### ISSUE TITLE
App not starting, when tried npm start

### ISSUE THREAD

**Issue by javeedrahman** [manosim/gitify#286]
Hi,
 i cloned the code and run npm install, then npm start i am getting error?

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/home/jargon-javi/projects/gitify/main.js:26:43)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at loadApplicationPackage (/home/jargon-javi/projects/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:288:12)
    at Object.<anonymous> (/home/jargon-javi/projects/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:330:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

Any Help Please.

**Comment by manosim** [comment]
Hello @javeedrahman! It looks like it is failing while trying to setup the "auto-update" functionality. Can you try deleting/commenting [https://github.com/manosim/gitify/blob/master/main.js#L24-L28](this)? You might have to comment any code referring to the variable `autoStart`. Will try to include this fix in v2!
